<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="D:/April2024/Automation_Projects/APIAutomationFramework/src/test/java/com/automationtestingrestassured/misc/DemoTest.java"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="8.001">
    <properties></properties>

            <testcase
                name="deleteBooking"
                time="0.013"
                classname="com.automationtestingrestassured.CRUD.TC01_Integration">

            <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
                <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
                io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)io.restassured.path.json.JsonPath.get(JsonPath.java:202)io.restassured.path.json.JsonPath.getString(JsonPath.java:352)com.automationtestingrestassured.CRUD.TC01_Integration.deleteBooking(TC01_Integration.java:106)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1597)org.testng.TestRunner.privateRun(TestRunner.java:739)org.testng.TestRunner.run(TestRunner.java:614)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
                    Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'M', no possible valid JSON value or punctuation could be recognized.
                    groovy.json.JsonLexer.nextToken(JsonLexer.java:86)groovy.json.JsonLexer$nextToken.call(Unknown Source)io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)io.restassured.path.json.JsonPath.get(JsonPath.java:202)io.restassured.path.json.JsonPath.getString(JsonPath.java:352)com.automationtestingrestassured.CRUD.TC01_Integration.deleteBooking(TC01_Integration.java:106)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1597)org.testng.TestRunner.privateRun(TestRunner.java:739)org.testng.TestRunner.run(TestRunner.java:614)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
                ]]>
            </failure>
    </testcase>


            <testcase
                name="testCreateBooking"
                time="6.726"
                classname="com.automationtestingrestassured.CRUD.TC01_Integration">
            </testcase>
            <testcase
                name="updateBooking"
                time="1.262"
                classname="com.automationtestingrestassured.CRUD.TC01_Integration">
            </testcase>
</testsuite>
